[package]
name = "tracing-oslog"
version = "0.2.0"
edition = "2021"

[dependencies]
tracing-core = "0.1"
tracing-subscriber = { version = "0.3", optional = true }

[features]
default = ["subscriber"]
subscriber = ["tracing-subscriber"]
